version: "3.12"

services:
  ml-backend:
    container_name: ml-backend
    build: .
    environment:
      - MODEL_DIR=/app/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
    ports:
      - "9090:9090"
